import type {
  RegimeReading,
  AssetScoreCard,
  CatalystEvent,
  TradeIdea,
  NarrativeOutput,
  MacroDashboardResponse,
} from './types'

export const fixtureRegime: RegimeReading = {
  regime: 'reflation',
  age_days: 14,
  conviction: 'high',
  recently_shifted: true,
  coherence_score: 0.82,
}

export const fixtureAssetScores: Record<string, AssetScoreCard> = {
  SPY: {
    asset: 'SPY',
    price: 5894.12,
    change_1d_pct: 0.67,
    change_5d_pct: 2.14,
    change_21d_pct: 4.89,
    score_5d: 78,
    score_10d: 72,
    score_21d: 68,
    iv_rank: 34,
    dominant_factor: 'earnings momentum',
    state_line: 'uptrend continuation',
    border_state: 'green',
  },
  VIX: {
    asset: 'VIX',
    price: 14.32,
    change_1d_pct: -3.21,
    change_5d_pct: -8.45,
    change_21d_pct: -12.67,
    score_5d: 22,
    score_10d: 28,
    score_21d: 31,
    iv_rank: 18,
    dominant_factor: 'vol compression',
    state_line: 'subdued risk environment',
    border_state: 'yellow',
  },
  GLD: {
    asset: 'GLD',
    price: 217.45,
    change_1d_pct: -0.34,
    change_5d_pct: 0.89,
    change_21d_pct: 3.12,
    score_5d: 45,
    score_10d: 51,
    score_21d: 55,
    iv_rank: 42,
    dominant_factor: 'real rates declining',
    state_line: 'consolidation above support',
    border_state: 'muted',
  },
  SLV: {
    asset: 'SLV',
    price: 28.91,
    change_1d_pct: 1.23,
    change_5d_pct: 3.56,
    change_21d_pct: 7.89,
    score_5d: 68,
    score_10d: 62,
    score_21d: 58,
    iv_rank: 47,
    dominant_factor: 'industrial demand',
    state_line: 'breakout from base',
    border_state: 'green',
  },
  DXY: {
    asset: 'DXY',
    price: 103.78,
    change_1d_pct: -0.45,
    change_5d_pct: -1.12,
    change_21d_pct: -2.89,
    score_5d: 35,
    score_10d: 39,
    score_21d: 42,
    iv_rank: 28,
    dominant_factor: 'carry trade unwind',
    state_line: 'weakening trend',
    border_state: 'yellow',
  },
  WTI: {
    asset: 'WTI',
    price: 72.34,
    change_1d_pct: 2.15,
    change_5d_pct: 4.67,
    change_21d_pct: 8.23,
    score_5d: 82,
    score_10d: 76,
    score_21d: 71,
    iv_rank: 56,
    dominant_factor: 'OPEC+ supply discipline',
    state_line: 'reflation bid active',
    border_state: 'green',
  },
  BRENT: {
    asset: 'BRENT',
    price: 76.12,
    change_1d_pct: 1.98,
    change_5d_pct: 4.23,
    change_21d_pct: 7.45,
    score_5d: 79,
    score_10d: 74,
    score_21d: 69,
    iv_rank: 52,
    dominant_factor: 'demand recovery',
    state_line: 'confirming WTI lead',
    border_state: 'muted',
  },
}

export const fixtureCatalysts: CatalystEvent[] = [
  {
    event_date: '2026-05-07',
    event_time: '08:30',
    event_type: 'employment',
    event_label: 'Non-Farm Payrolls',
    assets_impacted: ['SPY', 'VIX', 'DXY'],
    consensus_value: 185000,
    prior_value: 177000,
    surprise_weight: 0.85,
    straddle_implied_move: 1.2,
  },
  {
    event_date: '2026-05-08',
    event_time: '10:00',
    event_type: 'sentiment',
    event_label: 'ISM Services PMI',
    assets_impacted: ['SPY', 'VIX', 'DXY'],
    consensus_value: 51.8,
    prior_value: 50.8,
    surprise_weight: 0.65,
    straddle_implied_move: 0.8,
  },
  {
    event_date: '2026-05-10',
    event_time: '08:30',
    event_type: 'inflation',
    event_label: 'CPI (YoY)',
    assets_impacted: ['SPY', 'GLD', 'DXY', 'WTI'],
    consensus_value: 2.9,
    prior_value: 3.1,
    surprise_weight: 0.92,
    straddle_implied_move: 1.5,
  },
  {
    event_date: '2026-05-12',
    event_time: null,
    event_type: 'geo',
    event_label: 'OPEC+ Ministerial Meeting',
    assets_impacted: ['WTI', 'BRENT'],
    consensus_value: null,
    prior_value: null,
    surprise_weight: 0.70,
    straddle_implied_move: 3.2,
  },
  {
    event_date: '2026-05-14',
    event_time: '14:00',
    event_type: 'monetary',
    event_label: 'FOMC Minutes Release',
    assets_impacted: ['SPY', 'VIX', 'GLD', 'DXY'],
    consensus_value: null,
    prior_value: null,
    surprise_weight: 0.78,
    straddle_implied_move: 0.9,
  },
  {
    event_date: '2026-05-16',
    event_time: '08:30',
    event_type: 'inflation',
    event_label: 'PPI (MoM)',
    assets_impacted: ['SPY', 'DXY'],
    consensus_value: 0.2,
    prior_value: 0.3,
    surprise_weight: 0.55,
    straddle_implied_move: 0.6,
  },
  {
    event_date: '2026-05-18',
    event_time: '10:00',
    event_type: 'sentiment',
    event_label: 'U of Michigan Consumer Sentiment',
    assets_impacted: ['SPY', 'VIX'],
    consensus_value: 77.5,
    prior_value: 76.2,
    surprise_weight: 0.45,
    straddle_implied_move: 0.5,
  },
  {
    event_date: '2026-05-21',
    event_time: '10:30',
    event_type: 'inventory',
    event_label: 'EIA Crude Oil Inventories',
    assets_impacted: ['WTI', 'BRENT'],
    consensus_value: null,
    prior_value: null,
    surprise_weight: 0.60,
    straddle_implied_move: 2.1,
  },
]

export const fixtureTradeIdeas: TradeIdea[] = [
  {
    asset: 'SPY',
    direction: 'LONG',
    dte_range: [30, 45],
    structure: 'Call Spread',
    entry_condition: 'SPY > 5880 on volume',
    invalidation: 'SPY < 5780',
    conviction: 'high',
    iv_rank_context: 'IV Rank 34 — favorable for debit spreads',
    confirmations: 3,
    half_size: false,
  },
  {
    asset: 'GLD',
    direction: 'LONG',
    dte_range: [45, 60],
    structure: 'Call',
    entry_condition: 'GLD holds 215 support',
    invalidation: 'GLD < 210',
    conviction: 'medium',
    iv_rank_context: 'IV Rank 42 — moderate premium, directional debit OK',
    confirmations: 2,
    half_size: true,
  },
]

export const fixtureNarrative: NarrativeOutput = {
  date: '2026-05-05',
  regime_narrative:
    'Reflation regime intact at Day 14. Cohesive macro signal across equities and commodities — SPY confirming uptrend, WTI/BRENT bid with OPEC+ discipline, VIX compressed. Gold flat but holding support. Dollar weakening supports the reflation thesis.',
  trade_narrative:
    'Primary: SPY call spread 5880/6000 in 30-45 DTE on continuation. Secondary: GLD call at 215 support with half size — real rates declining could reignite bid if CPI prints soft. Avoid VIX plays in this compressed environment.',
  model_used: 'claude-3.5-sonnet',
}

export const fixtureDashboard: MacroDashboardResponse = {
  regime: fixtureRegime,
  asset_scores: fixtureAssetScores,
  catalysts: fixtureCatalysts,
  trade_ideas: fixtureTradeIdeas,
  narrative: fixtureNarrative,
  last_refresh: '2026-05-05T14:30:00Z',
  stale: false,
}