import React from 'react'
import { color, font } from '../../../lib/theme'
import type { NarrativeOutput } from './types'

interface TodaysReadProps {
  narrative: NarrativeOutput | null
  loading?: boolean
}

const TodaysRead: React.FC<TodaysReadProps> = ({ narrative, loading }) => {
  if (loading) {
    return (
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '24px',
          color: color.textTertiary,
          fontFamily: font.sans,
          fontSize: '13px',
        }}
      >
        Loading narrative...
      </div>
    )
  }

  if (!narrative) {
    return (
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '24px',
          color: color.textTertiary,
          fontFamily: font.sans,
          fontSize: '13px',
        }}
      >
        Narrative unavailable
      </div>
    )
  }

  const regimeParagraphs = narrative.regime_narrative.split('\n\n')
  const tradeParagraphs = narrative.trade_narrative.split('\n\n')

  return (
    <div
      style={{
        minHeight: '160px',
        maxHeight: '300px',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
        position: 'relative',
      }}
    >
      <button
        className="bb-btn"
        style={{
          position: 'absolute',
          top: '0',
          right: '0',
          zIndex: 2,
          fontSize: '10px',
          padding: '3px 8px',
        }}
      >
        &#8635; Regenerate
      </button>

      <div style={{ paddingTop: '0', paddingRight: '70px' }}>
        <div
          style={{
            ...{
              fontFamily: font.sans,
              fontSize: '13px',
              lineHeight: 1.7,
              color: color.textSecondary,
            },
          }}
        >
          <div style={{ marginBottom: '8px', fontWeight: 600, color: color.textPrimary, fontSize: '11px', letterSpacing: '0.02em', textTransform: 'uppercase' as const }}>
            Regime
          </div>
          {regimeParagraphs.map((p, i) => (
            <p key={`r-${i}`} style={{ margin: 0, marginBottom: '12px' }}>
              {p}
            </p>
          ))}

          <div style={{ marginTop: '4px', marginBottom: '8px', fontWeight: 600, color: color.textPrimary, fontSize: '11px', letterSpacing: '0.02em', textTransform: 'uppercase' as const }}>
            Trade Thesis
          </div>
          {tradeParagraphs.map((p, i) => (
            <p key={`t-${i}`} style={{ margin: 0, marginBottom: '12px' }}>
              {p}
            </p>
          ))}
        </div>

        <div
          style={{
            fontFamily: font.sans,
            fontSize: '10px',
            color: color.textTertiary,
            paddingTop: '8px',
            borderTop: `1px solid ${color.borderSubtle}`,
            marginTop: '4px',
          }}
        >
          Generated by {narrative.model_used} &middot; {narrative.date}
        </div>
      </div>
    </div>
  )
}

export default TodaysRead